openapi: 3.0.3
info:
  title: Laravel
  description: ''
  version: 1.0.0
servers:
  -
    url: 'http://localhost'
paths:
  /api/login:
    post:
      summary: ''
      operationId: postApiLogin
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  description: 'Must not be greater than 250 characters.'
                  example: eprohaska@example.net
                password:
                  type: string
                  description: 'Must be at least 8 characters.'
                  example: 'HtHI^|aC:7-'
              required:
                - email
                - password
      security: []
  /api/logout:
    post:
      summary: ''
      operationId: postApiLogout
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      security: []
  '/api/history/score/{userID}':
    get:
      summary: 'Get the highest for particular user.'
      operationId: getTheHighestForParticularUser
      description: ''
      parameters: []
      responses:
        401:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: Unauthenticated.
                properties:
                  message:
                    type: string
                    example: Unauthenticated.
      tags:
        - Endpoints
      security: []
    parameters:
      -
        in: path
        name: userID
        description: ''
        example: sunt
        required: true
        schema:
          type: string
  /api/history:
    get:
      summary: 'Display a listing of the resource.'
      operationId: displayAListingOfTheResource
      description: ''
      parameters: []
      responses:
        401:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: Unauthenticated.
                properties:
                  message:
                    type: string
                    example: Unauthenticated.
      tags:
        - Endpoints
      security: []
    post:
      summary: 'Store a newly created resource in storage.'
      operationId: storeANewlyCreatedResourceInStorage
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                userID:
                  type: string
                  description: 'Must not be greater than 120 characters.'
                  example: wqcjlgnxetjnsnzzqtpwnkfvf
                score:
                  type: string
                  description: 'Must not be greater than 250 characters.'
                  example: dmqtugcnjncaodhhh
              required:
                - userID
                - score
      security: []
  '/api/history/{id}':
    get:
      summary: 'Display the user history information.'
      operationId: displayTheUserHistoryInformation
      description: ''
      parameters: []
      responses:
        401:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: Unauthenticated.
                properties:
                  message:
                    type: string
                    example: Unauthenticated.
      tags:
        - Endpoints
      security: []
    parameters:
      -
        in: path
        name: id
        description: 'The ID of the history.'
        example: omnis
        required: true
        schema:
          type: string
  /api/users:
    get:
      summary: 'Display a listing of the resource.'
      operationId: displayAListingOfTheResource
      description: ''
      parameters: []
      responses:
        401:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: Unauthenticated.
                properties:
                  message:
                    type: string
                    example: Unauthenticated.
      tags:
        - Endpoints
      security: []
    post:
      summary: 'Store a newly created resource in storage.'
      operationId: storeANewlyCreatedResourceInStorage
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: ''
                  example: quis
                email:
                  type: string
                  description: 'Must be a valid email address.'
                  example: rosalee.price@example.org
                password:
                  type: string
                  description: 'Must be at least 8 characters.'
                  example: 'Jno@Xq+3#x-{ZD'
              required:
                - name
                - email
                - password
      security: []
tags:
  -
    name: Endpoints
    description: ''
